run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,10 @@
-#!/usr/bin/python3
-print("Best School")
+#!/bin/bash
+
+# Check if the PYFILE variable is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE variable is not set."
+    exit 1
+fi
+
+# Run the Python script
+python3 "$PYFILE"
